const MEMBER_ORG = "Member";
const ADMIN_ORG = "Admin";

const STATUS_INACTIVE = "";

const ASSET_PREFIX_USER = "USER";
const ASSET_PREFIX_ADMIN_USER = "ADMIN_USER";
const ASSET_PREFIX_CONTRACT = "CONTRACT";
const ASSET_PREFIX_DISCOUTING = "DISCOUNTING";
const ASSET_PREFIX_LOC = "LOC";
const ASSET_PREFIX_INVOICE = "INVOICE";
const ASSET_PREFIX_TRAIL = "TRAIL";
const ASSET_PREFIX_ENC = "ENC";

const RSA_LABEL = "RSA_LABEL";
const RSA_SEED = "RSA_SEED";
const AESKEY = "AESKEY";
const IV = "IV";
const NEW_AESKEY = "NEW_AESKEY";
const NEW_IV = "NEW_IV";

const STAKE_HOLDERS = "STAKE_HOLDERS";
const SELLER_ADDRESS = "SELLER_ADDRESS";
const BUYER_ADDRESS = "BUYER_ADDRESS";
const SHIPPER_ADDRESS = "SHIPPER_ADDRESS";
const INSPECTOR_ADDRESS = "INSPECTOR_ADDRESS";
const INSPECTOR_SELLER_ADDRESS = "INSPECTOR_SELLER_ADDRESS";
const INSPECTOR_BUYER_ADDRESS = "INSPECTOR_BUYER_ADDRESS";
const INSPECTOR_THIRD_PARTY_ADDRESS = "INSPECTOR_THIRD_PARTY_ADDRESS";
const BROKER_ADDRESS = "BROKER_ADDRESS";
const BANK_ADDRESS = "BANK_ADDRESS";
const BANK_SUPPLIER_ADDRESS = "BANK_SUPPLIER_ADDRESS";
const BANK_BUYER_ADDRESS = "BANK_BUYER_ADDRESS";
const STEVEDORE_ADDRESS = "STEVEDORE_ADDRESS";
const CUSTOM_INSPECTOR_ADDRESS = "CUSTOM_INSPECTOR_ADDRESS";
const INSURER_ADDRESS = "INSURER_ADDRESS";
const INSURER_COMMODITY_ADDRESS = "INSURER_COMMODITY_ADDRESS";
const INSURER_TRADE_ADDRESS = "INSURER_TRADE_ADDRESS";
const QUANTITY = "QUANTITY";
const PRICE = "PRICE";
const LOC_ADDRESS = "LOC_ADDRESS";
const QUANTITY_HASH = "QUANTITY_HASH";
const USER_ARRAY = "USER_ARRAY";

const CONTRACT_NUMBER = "CONTRACT_NUMBER";
const ASSET_NUMBER = "ASSET_NUMBER";
const CONTRACT_DATA = "CONTRACT_DATA";
const COMMODITY_NAME = "COMMODITY_NAME";
const SERVICE_NAME = "SERVICE_NAME";
const SPECIFICATIONS = "SPECIFICATIONS";
const CONTRACT_TNC = "CONTRACT_TNC";
const CONTRACT_TYPE = "CONTRACT_TYPE";
const PAYMENT_TYPE = "PAYMENT_TYPE";
const MEASURING_UNIT = "MEASURING_UNIT";
const TOTAL_AMOUNT = "TOTAL_AMOUNT";
const CURRENCY_CODE = "CURRENCY_CODE";
const LAYCAN_START_TIME = "LAYCAN_START_TIME";
const LAYCAN_END_TIME = "LAYCAN_END_TIME";
const DATE_OF_SHIPMENT = "DATE_OF_SHIPMENT";
const LOAD_PORT = "LOAD_PORT";
const UNLOAD_PORT = "UNLOAD_PORT";
const LOAD_COUNTRY_CODE = "LOAD_COUNTRY_CODE";
const UNLOAD_COUNTRY_CODE = "UNLOAD_COUNTRY_CODE";
const PRICE_ADJUSTMENT_CLAUSE_HASH = "PRICE_ADJUSTMENT_CLAUSE_HASH";
const DISPUTE_RESOLUTION_CLAUSE_HASH = "DISPUTE_RESOLUTION_CLAUSE_HASH";
const PAYMENT_TERMS_HASH = "PAYMENT_TERMS_HASH";
const INSURANCE_TERMS_HASH = "INSURANCE_TERMS_HASH";
const TERMINATION_CLAUSE_HASH = "TERMINATION_CLAUSE_HASH";
const CONTRACT_REFERENCE = "CONTRACT_REFERENCE";
const REJECTION_LEVEL = "REJECTION_LEVEL";
const DOCUMENTS = "DOCUMENTS";
const DOCUMENT_NAME = "DOCUMENT_NAME";
const DOCUMENT_DETAILS = "DOCUMENT_DETAILS";
const DOCUMENT_HASH = "DOCUMENT_HASH";

const FINANCE_ID = "FINANCE_ID";
const REQUESTED_AMOUNT = "REQUESTED_AMOUNT";
const APPROVED_AMOUNT = "APPROVED_AMOUNT";
const DISCOUNTING_TYPE = "DISCOUNTING_TYPE";
const REFERENCE_ID = "REFERENCE_ID";
const REFERENCE_DATE = "REFERENCE_DATE";
const REFERENCE_AMOUNT = "REFERENCE_AMOUNT";
const LOAN_ID = "LOAN_ID";
const DISCOUTING_STATUS = "DISCOUTING_STATUS";
const DISBURSEMENT_REFERENCE = "DISBURSEMENT_REFERENCE";
const REPAYMENT_REFERENCE = "REPAYMENT_REFERENCE";
const DISBURSEMENT_DATE = "DISBURSEMENT_DATE";

const USER_UPDATE_USERTYPE = 1;
const USER_UPDATE_USERSTATUS = 2;
const USER_UPDATE_USERRSAKEY = 3;
const USER_UPDATE_USERTYPE_USERSTATUS = 4;
const USER_UPDATE_USERTYPE_USERRSAKEY = 5;
const USER_UPDATE_USERSTATUS_USERRSAKEY = 6;
const USER_UPDATE_USERTYPE_USERSTATUS_USERRSAKEY = 7;


